import { Venue } from '../types';

export const MOCK_VENUES: Venue[] = [
  {
    id: 'hannahs',
    name: "Hannah's Bar & Grille",
    type: "League HQ / Dive Bar",
    status: 'buzzing',
    checkIns: 42,
    deal: "$4 Rainier Pints & 1/2 Price Nachos",
    dealEndsIn: 45,
    vibe: "High Energy",
    coordinates: { x: 10, y: 10 },
    leagueEvent: null, 
    isHQ: true,
    alertTags: ['pool', 'food', 'sports'],
    description: "The beating heart of the Olympia Bar League. Known for heavy pours, the best breakfast in town, and being the official meetup spot for league champions. Two pool tables, pull tabs, and no pretension.",
    address: "123 5th Ave SW, Olympia, WA",
    hours: "7AM - 2AM Daily",
    phone: "(360) 555-0100"
  },
  {
    id: 'legends',
    name: "Legends Arcade",
    type: "Arcade Bar",
    status: 'buzzing',
    checkIns: 38,
    deal: "Free Tokens w/ Pitcher",
    dealEndsIn: 60,
    vibe: "Retro Gaming",
    coordinates: { x: 12, y: 12 },
    leagueEvent: 'arcade',
    alertTags: ['arcade', 'beer'],
    description: "Over 50 vintage cabinets, pinball wizards, and a killer craft beer selection. Home of the High Score challenge.",
    address: "109 Washington St NE",
    hours: "4PM - 12AM",
    phone: "(360) 555-0199"
  },
  {
    id: 'chinaclipper',
    name: "China Clipper",
    type: "Lounge / Karaoke",
    status: 'lively',
    checkIns: 31,
    deal: "$5 Well Drinks",
    dealEndsIn: 120,
    vibe: "Late Night Classic",
    coordinates: { x: 14, y: 14 },
    leagueEvent: 'karaoke',
    alertTags: ['karaoke', 'cocktails'],
    description: "Olympia's legendary karaoke lounge. Dark lights, strong drinks, and local legends on the mic every night of the week.",
    address: "402 4th Ave E",
    hours: "2PM - 2AM",
    phone: "(360) 555-0200"
  },
  {
    id: 'well80',
    name: "Well 80 Brewhouse",
    type: "Brewery / Artie's Home",
    status: 'lively',
    checkIns: 18,
    deal: "$5 Artesian IPAs",
    dealEndsIn: 120,
    vibe: "Social / Warm",
    coordinates: { x: 20, y: 15 },
    leagueEvent: 'trivia',
    alertTags: ['trivia', 'beer', 'food'],
    description: "Brewing with the famous Artesian water. Home of Artie the AI and the best burger on 4th Ave.",
    address: "514 4th Ave E",
    hours: "11AM - 10PM",
    phone: "(360) 555-0800"
  },
  {
    id: 'brotherhood',
    name: "The Brotherhood",
    type: "Lounge",
    status: 'chill',
    checkIns: 8,
    vibe: "Cozy / Classic",
    deal: "$6 Slushies",
    dealEndsIn: 180,
    coordinates: { x: 5, y: 30 },
    leagueEvent: 'bingo',
    alertTags: ['bingo', 'cocktails', 'pool'],
    description: "A historic lounge with a modern edge. Famous for shuffleboard, dark corners, and the patio.",
    address: "119 Capitol Way N",
    hours: "4PM - 2AM",
    phone: "(360) 555-0300"
  },
  {
    id: 'threemags',
    name: "Three Magnets",
    type: "Brewery / Cornhole",
    status: 'chill',
    checkIns: 12,
    deal: "$10 Burger & Beer",
    dealEndsIn: 180,
    vibe: "Relaxed",
    coordinates: { x: 25, y: 5 },
    leagueEvent: 'cornhole',
    alertTags: ['cornhole', 'beer', 'food'],
    description: "Community focused brewery with a massive patio and non-alcoholic options.",
    address: "600 Franklin St SE",
    hours: "12PM - 9PM",
    phone: "(360) 555-0400"
  },
  {
    id: 'ryer',
    name: "Rhythms Coffee",
    type: "Venue",
    status: 'chill',
    checkIns: 5,
    vibe: "Acoustic",
    coordinates: { x: 30, y: 30 },
    leagueEvent: 'openmic',
    alertTags: ['openmic', 'live_music', 'coffee'],
    description: "Live music venue and coffee roaster. The sober-friendly spot in the League.",
    address: "210 4th Ave W",
    hours: "7AM - 8PM",
    phone: "(360) 555-0500"
  },
  {
    id: 'cryptatropa',
    name: "Cryptatropa",
    type: "Goth Bar",
    status: 'lively',
    checkIns: 24,
    deal: "Absinthe Drip Special",
    dealEndsIn: 90,
    vibe: "Dark / Moody",
    coordinates: { x: 15, y: 25 },
    leagueEvent: null,
    alertTags: ['cocktails', 'live_music'],
    description: "Olympia's premier goth bar. Absinthe, darkwave, and atmosphere you can cut with a knife.",
    address: "421 4th Ave E",
    hours: "5PM - 2AM",
    phone: "(360) 555-0666"
  }
];