import { db } from './firebaseAdmin';

const venues = [
    // --- DOWNTOWN WALKABLE LOOP ---
    {
        id: 'well-80',
        name: 'Well 80 Artesian Brewing',
        type: 'Brewery',
        makerType: 'Brewery',
        status: 'lively',
        vibe: 'Home of Artie and built on the Artesian Well',
        insiderVibe: "It's slick. Maybe too slick? It feels like a brewpub, not a bar—lots of polished concrete and big screens. But you can't argue with the history. Tapping that well is a boss move, and the 'Leopold's #1 Lager' is legit respect to the old school. It's where you go to watch the game, not to hide from the world.",
        originStory: "They literally drilled a hole in the floor to tap into the same mythical aquifer that made Olympia Beer famous in 1896. It's a shiny, high-energy brewpub built directly on top of history, serving crisp lagers made from the 'Water' that put this town on the map.",
        geoLoop: 'Downtown_Walkable',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        checkIns: 0,
        coordinates: { x: 55, y: 85 },
        location: { lat: 47.0424, lng: -122.9009 },
        address: '514 4th Ave E, Olympia, WA 98501',
        isActive: true,
        isVisible: true,
        isHistoricalAnchor: true,
        historySnippet: "Taste the water (literally) from the original Artesian Well.",
        isPaidLeagueMember: true,
        flashDeals: [{
            id: 'fd-w80-01',
            venueId: 'well-80',
            title: '$2 Pretzels & Cheese',
            description: 'Flash Deal: $2 Pretzels valid for next 45 mins.',
            startTime: Date.now(),
            endTime: Date.now() + 45 * 60 * 1000,
            isApproved: true,
            termsAccepted: true,
            active: true
        }],
        activeFlashDealId: 'fd-w80-01',
        deal: "$2 Pretzels & Cheese",
        dealEndsIn: 45, // Flash Deal (Minutes remaining)
    },
    {
        id: 'ilk-lodge',
        name: 'Ilk Lodge',
        type: 'Brewery',
        makerType: 'Brewery',
        status: 'chill',
        vibe: 'Twin Peaks meets Skate Rat',
        insiderVibe: "Pat Jansen is a legend. He ran the brewing at Three Mags, then Matchless, now this. The vibe is 'Twin Peaks meets Skate Rat.' It's cool without trying. And the burgers? Greasy, smashy perfection. This replaces Fish Tale as the soul of downtown brewing.",
        originStory: "When the legendary Fish Tale Brewpub died, the former brewers of Matchless and Three Magnets didn't just mourn—they took it over. Now it's a 'lodge' serving high-technique ales and arguably the best smash burgers in the county, resurrecting the most iconic corner in Olympia nightlife.",
        geoLoop: 'Downtown_Walkable',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        checkIns: 0,
        coordinates: { x: 48, y: 72 },
        location: { lat: 47.0435, lng: -122.9040 },
        address: '515 Jefferson St SE, Olympia, WA 98501',
        isActive: true,
        isVisible: true
    },
    {
        id: 'headless-mumby',
        name: 'Headless Mumby Brewing Company',
        type: 'Brewery',
        makerType: 'Brewery',
        status: 'chill',
        vibe: 'Union-made lagers; no IPAs here',
        insiderVibe: "Finally. A place that doesn't taste like a pine cone. Alex is a worker; he's union. This place has 'working class hero' vibes but in a cozy way. It feels like a living room. No kitchen, which is perfect—let people order pizza from Vic's across the street. The staff doesn't have to fuss with food, they just pour beer.",
        originStory: "Founded by Alex Maffeo, a union tradesman who decided the world had enough IPAs, this Westside gem brews only lagers—crisp, clean, and unpretentious. It's named after a Warren Zevon song about a headless gunner and an old local shingle mill, proving they care more about cool stories and cold beer than chasing trends.",
        geoLoop: 'Downtown_Walkable',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        checkIns: 0,
        coordinates: { x: 30, y: 70 },
        location: { lat: 47.0480, lng: -122.9250 },
        address: '232 Division St NW, Olympia, WA 98502',
        isActive: true,
        isVisible: true
    },
    {
        id: 'three-magnets',
        name: 'Three Magnets Brewing Co.',
        type: 'Brewery',
        makerType: 'Brewery',
        status: 'lively',
        vibe: 'The Community Hub & NA Pioneers',
        insiderVibe: "The center of the 'Sober Squad' league track. Home of 'Self Care' non-alcoholic beer and Scherler Sundays.",
        originStory: "Sara and Nate Reilly built a 'Third Place' for Olympia. Their pivot to 'Self Care' (a non-alcoholic line) has made them a national player in the sober-curious movement.",
        geoLoop: 'Downtown_Walkable',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        isSoberFriendly: true,
        checkIns: 0,
        coordinates: { x: 52, y: 65 },
        location: { lat: 47.0438, lng: -122.8994 },
        address: '600 Franklin St SE, Suite 105, Olympia, WA 98501',
        isActive: true,
        isVisible: true
    },
    {
        id: 'whitewood-cider',
        name: 'Whitewood Cider Co.',
        type: 'Cidery',
        makerType: 'Cidery',
        status: 'chill',
        vibe: 'The Teeny Tiny Taproom',
        insiderVibe: "The Teeny Tiny Taproom is the definition of cool. It's barely a room. You sit on the patio, you drink cider that tastes like actual apples, not candy. It's legit. No frills, just product.",
        originStory: "Dave White was writing about cider before anyone was drinking it. He founded the Northwest Cider Association and then put his money where his mouth was, creating a 'Teeny Tiny Taproom' in downtown Oly that is smaller than most walk-in closets but pours the most respected heirloom ciders in the state. They recently moved production to Tenino, but the heart remains in that tiny room on 4th Ave.",
        geoLoop: 'Downtown_Walkable',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        isBoutique: true,
        isLowCapacity: true,
        checkIns: 0,
        coordinates: { x: 60, y: 40 },
        location: { lat: 47.0470, lng: -122.8980 },
        address: '728 4th Ave E, Olympia, WA 98501',
        isActive: true,
        isVisible: true
    },
    {
        id: 'endless-sound-cellars',
        name: 'Endless Sound Cellars',
        type: 'Winery',
        makerType: 'Winery',
        status: 'chill',
        vibe: 'The Urban Cellar',
        insiderVibe: "A sleek, industrial cellar feel inside the 222 Market. Perfect for a sophisticated evening flight.",
        originStory: "Mark Bosso brought his winemaking chops from Woodinville to the heart of downtown Olympia. It's the perfect 'urban winery' experience.",
        geoLoop: 'Downtown_Walkable',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        checkIns: 0,
        coordinates: { x: 65, y: 45 },
        location: { lat: 47.0465, lng: -122.8970 },
        address: '222 Capitol Way N, Olympia, WA 98501',
        isActive: true,
        isVisible: true
    },

    // --- WAREHOUSE TUMWATER LOOP ---
    {
        id: 'matchless-brewing',
        name: 'Matchless Brewing',
        type: 'Brewery',
        makerType: 'Brewery',
        status: 'lively',
        vibe: 'The Hype Beast; 80s Synth-Pop Vibes',
        insiderVibe: "The branding is incredible. Best cans in the county. The vibe in the taproom is industrial but energetic. It feels like a place where beer nerds congregate. It's legit.",
        originStory: "Born from the creative minds of Three Magnets alumni, Matchless exploded onto the scene with branding that looks like an 80s synth-pop album cover and beer that pushes every boundary. They don't just make IPAs; they make hazy, juicy, complex hop-bombs that win awards and wreck palates in the best way possible.",
        geoLoop: 'Warehouse_Tumwater',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        checkIns: 0,
        coordinates: { x: 50, y: 15 },
        location: { lat: 46.9930, lng: -122.9150 },
        address: '8036 River Dr SE #208, Tumwater, WA 98501',
        isActive: true,
        isVisible: true
    },
    {
        id: 'triceratops-brewing',
        name: 'Triceratops Brewing Company',
        type: 'Brewery',
        makerType: 'Brewery',
        status: 'chill',
        vibe: 'Approachably dangerous, family founded',
        insiderVibe: "The Strawberry Golden is a gateway drug for my wine drinkers. It's sophisticated enough, not cloyingly sweet. It allows a wine drinker to participate in a brewery crawl without grimacing.",
        originStory: "Rob and Kelly Horn moved here from New Jersey and started brewing in their garage before taking over a warehouse space near the airport. Named after their three kids (the 'three horns'), they brew approachable, dangerously drinkable beers like the 'Strawberry Golden Ale' that convert even non-beer drinkers.",
        geoLoop: 'Warehouse_Tumwater',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        checkIns: 0,
        coordinates: { x: 51, y: 16 },
        location: { lat: 46.9928, lng: -122.9148 },
        address: '8036 River Dr SE, Suite 203, Tumwater, WA 98501',
        isActive: true,
        isVisible: true
    },
    {
        id: 'rainwater-brewing',
        name: 'Rainwater Brewing',
        type: 'Brewery',
        makerType: 'Brewery',
        status: 'chill',
        vibe: 'The Merchant Mariner; Steady hand at the wheel',
        insiderVibe: "I liked Hoh River; it was weird. Rainwater feels like a steady hand took the wheel. The merchant mariner backstory is cool—authentic grit. It feels like a place where actual work gets done.",
        originStory: "Gavin Rainwater, a former merchant mariner who spent years at sea, dropped anchor in Tumwater to take over the old Hoh River Brewery. It's a true 'local's local' spot, serving unpretentious suds and honest food in a space that feels like a warm, dry cabin in the middle of a PNW storm.",
        geoLoop: 'Warehouse_Tumwater',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        checkIns: 0,
        coordinates: { x: 45, y: 20 },
        location: { lat: 47.0125, lng: -122.9180 },
        address: '2442 Mottman Rd SW, Tumwater, WA 98512',
        isActive: true,
        isVisible: true
    },
    {
        id: 'mount-olympus',
        name: 'Mount Olympus Brewing (Tumwater Taps)',
        type: 'Brewery',
        makerType: 'Brewery',
        status: 'lively',
        vibe: 'The District Anchor; Aberdeen Grit',
        insiderVibe: "Aberdeen grit in a polished Tumwater building. Rowdy in a good way, designed for loud laughs and big groups.",
        originStory: "A martial arts-loving brewery from Aberdeen that decided to conquer the valley. They are the new anchor of the Tumwater Craft District.",
        geoLoop: 'Warehouse_Tumwater',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        checkIns: 0,
        coordinates: { x: 48, y: 12 },
        location: { lat: 46.9950, lng: -122.9050 },
        address: '4242 Capitol Blvd SE, Suite 100, Tumwater, WA 98501',
        isActive: true,
        isVisible: true
    },

    // --- DESTINATION QUESTS ---
    {
        id: 'top-rung',
        name: 'Top Rung Brewing Company',
        type: 'Brewery',
        makerType: 'Brewery',
        status: 'chill',
        vibe: 'The Outpost; precision and brotherhood',
        insiderVibe: "It's in a warehouse district in Lacey. It's not 'cool' in the hipster sense, but it's honest. It's where you go after a shift. I respect it. No pretense.",
        originStory: "Founded by Casey Sobol and Jason Stoltz, two career firefighters who spent their downtime perfecting recipes, this Lacey brewery is built on service, precision, and the brotherhood of the firehouse. It's an unpretentious warehouse taproom where the 'My Dog Scout Stout' has won more medals than most generals.",
        geoLoop: 'Destination_Quest',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        checkIns: 0,
        coordinates: { x: 85, y: 15 },
        location: { lat: 47.0940, lng: -122.7650 },
        address: '8343 Hogum Bay Ln NE, Suite E, Lacey, WA 98516',
        isActive: true,
        isVisible: true
    },
    {
        id: 'sandstone-distillery',
        name: 'Sandstone Distillery',
        type: 'Distillery',
        makerType: 'Distillery',
        status: 'chill',
        vibe: 'The Pilgrimage; Rugged and Authentic',
        insiderVibe: "A world-class educational stop. The bacon whiskey is a conversation starter, but the gin is the real deal.",
        originStory: "John Bourdon built a shrine to Tenino's stone-carving history. Grain-to-glass ruggedness fueled by locally grown grain and cooled by rainwater.",
        geoLoop: 'Destination_Quest',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        checkIns: 0,
        coordinates: { x: 70, y: 10 },
        location: { lat: 46.8570, lng: -122.8530 },
        address: '842 Wright Rd SE, Tenino, WA 98589',
        isActive: true,
        isVisible: true
    },
    {
        id: 'talking-cedar',
        name: 'Talking Cedar',
        type: 'Distillery',
        makerType: 'Distillery',
        status: 'lively',
        vibe: 'The Monument; Sovereign Spirits',
        insiderVibe: "It took an act of Congress to build this. A monument to sovereignty and spirits, partnering with Heritage to build a state-of-the-art facility.",
        originStory: "The Chehalis Tribe fought to repeal an 1834 law banning distilleries on tribal land. It is a massive facility dedicated to craft and heritage.",
        geoLoop: 'Destination_Quest',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        checkIns: 0,
        coordinates: { x: 10, y: 10 },
        location: { lat: 46.8280, lng: -123.0030 },
        address: '19770 Sargent Rd SW, Rochester, WA 98579',
        isActive: true,
        isVisible: true
    },
    {
        id: 'axis-meads',
        name: 'Axis Meads',
        type: 'Cidery', // Closest type in existing schema
        makerType: 'Cidery',
        status: 'chill',
        vibe: 'The Rare Drop; Spiced Honey Adventures',
        insiderVibe: " Spicy habanero and ginger meads that drink like cocktails. Located in the heart of Lacey's industrial zone.",
        originStory: "Born from the back room of the legendary Skep & Skein. Dave Ross crafts meads that destroy the cloyingly sweet stereotype.",
        geoLoop: 'Destination_Quest',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        checkIns: 0,
        coordinates: { x: 82, y: 22 },
        location: { lat: 47.0580, lng: -122.7830 },
        address: '2633 Willamette Dr NE, Suite B, Lacey, WA 98516',
        isActive: true,
        isVisible: true
    },
    {
        id: 'stottle-winery',
        name: 'Stottle Winery',
        type: 'Winery',
        makerType: 'Winery',
        status: 'chill',
        vibe: 'The Industrial Anchor; Serious chemistry',
        insiderVibe: "High quality product. Josh knows his chemistry. It appeals to the 'Wine Snob' demographic.",
        originStory: "Josh Stottlemyer traded web development for winemaking, setting up shop in a Lacey industrial park to prove you don't need a chateau to make world-class Syrah. It's a serious winery for serious wine drinkers, stripping away the pretension to focus entirely on what's in the glass.",
        geoLoop: 'Destination_Quest',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        checkIns: 0,
        coordinates: { x: 83, y: 25 },
        location: { lat: 47.0585, lng: -122.7835 },
        address: '2641 Willamette Dr NE, Suite E, Lacey, WA 98516',
        isActive: true,
        isVisible: true
    },
    {
        id: 'medicine-creek',
        name: 'Medicine Creek Winery',
        type: 'Winery',
        makerType: 'Winery',
        status: 'chill',
        vibe: 'The Hideaway; Stagecoach-stop fantasy',
        insiderVibe: "Jim Myers (a dentist with a cowboy soul) transformed a potato barn into an 1800s New Orleans brothel-themed tasting room.",
        originStory: "Operating in the Nisqually Valley, this is a stagecoach-stop fantasy come to life, pouring big, bold Washington reds.",
        geoLoop: 'Destination_Quest',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        checkIns: 0,
        coordinates: { x: 90, y: 30 },
        location: { lat: 47.0550, lng: -122.7050 },
        address: '947 Old Pacific Hwy SE, Olympia, WA 98513',
        isActive: true,
        isVisible: true
    },
    {
        id: 'elk-pond-ales',
        name: 'Elk Pond Craft Ales',
        type: 'Brewery',
        makerType: 'Brewery',
        status: 'chill',
        vibe: 'The Easter Egg; Scavenger Hunt Target',
        insiderVibe: "We can't send people to them. They don't exist as a venue. But we can gamify the hunt. 'Find the Elk'—extra points for checking in a pint of Elk Pond at a partner bar. It encourages exploration of other venues.",
        originStory: "The 'Ghost Brewery' of Olympia. The Wilkinson family built a dedicated micro-brewery on their property in 2023, but they don't open their doors to the public. You have to hunt for their kegs at local taverns like Pints Barn or Character's Corner to taste their 'Gold Craft' creations.",
        physicalRoom: false,
        geoLoop: 'Destination_Quest',
        isVerifiedMaker: true,
        isLocalMaker: true,
        checkIns: 0,
        coordinates: { x: 80, y: 20 },
        isActive: true,
        isVisible: true,
        scavengerHunts: [
            {
                title: 'Find the Elk!',
                partnerVenues: ['brotherhood-lounge'],
                badgeId: 'elk-pond-finder'
            }
        ]
    },

    // --- RECONCILED VENUES (Added Dec 2025) ---
    {
        id: 'brotherhood-lounge',
        name: 'The Brotherhood Lounge',
        type: 'Lounge',
        vibe: 'Industrial grit, stiff drinks, and shuffleboard.',
        makerType: 'Brewery', // Legacy/Placeholder type
        status: 'lively',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 45, y: 55 },
        address: '119 Capitol Way N, Olympia, WA 98501',
        website: 'https://thebrotherhoodlounge.com/',
        // Happy Hour (Scheduled)
        happyHour: {
            startTime: '16:00',
            endTime: '19:00',
            description: '$4 Wells & $1 Off Drafts',
            days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
        },
        isHistoricalAnchor: true,
        historySnippet: "Rumored entrance to the tunnels and Oly's oldest bar.",
        leagueEvent: 'trivia',
        cheatCodeUrl: '/history/tunnels-of-olympia',
        isPaidLeagueMember: true
    },
    {
        id: 'mccoys-tavern',
        name: 'McCoy’s Tavern',
        type: 'Dive Bar',
        vibe: 'The legendary downtown dive. No frills.',
        status: 'lively',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 40, y: 50 },
        address: '418 4th Ave E, Olympia, WA 98501',
        website: 'https://www.experienceolympia.com/directory/mccoys-tavern/'
    },
    {
        id: 'eastside-club-tavern',
        name: 'The Eastside Club Tavern',
        type: 'Tavern',
        vibe: 'Old school olympia. Great beer selection.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 60, y: 60 },
        address: '410 4th Ave E, Olympia, WA 98501',
        website: 'http://www.theeastsideclub.com/'
    },
    {
        id: 'shiny-prize',
        name: 'Shiny Prize',
        type: 'Bar',
        vibe: 'Mid-century modern aesthetic with top-tier cocktails.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 35, y: 45 },
        website: 'https://www.shinyprize.com/'
    },
    {
        id: 'nicoles-bar',
        name: 'Nicole’s Bar',
        type: 'Bar',
        vibe: 'Downtown staple for good food and drinks.',
        status: 'lively',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 42, y: 52 },
        website: 'https://nicolesbar.com/'
    },
    {
        id: 'cryptatropa-bar',
        name: 'Cryptatropa Bar',
        type: 'Bar',
        vibe: 'Goth-industrial haven. Dark and moody.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 38, y: 48 },
        website: 'https://www.thecryptbar.com/'
    },
    {
        id: 'jakes-on-4th',
        name: 'Jake’s on 4th',
        type: 'Bar',
        vibe: 'Classic bar returned to its roots.',
        status: 'lively',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 41, y: 51 },
        website: 'https://www.southsoundreport.com/p/jake-s-on-4th-returns-to-downtown-olympia'
    },
    {
        id: 'filibuster',
        name: 'Filibuster',
        type: 'Cocktail Bar',
        vibe: 'Upscale cocktails and lounge atmosphere.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 44, y: 54 },
        website: 'https://filibusterlounge.com/'
    },
    {
        id: 'cheeky-martini-lounge',
        name: 'Cheeky Martini Lounge',
        type: 'Lounge',
        vibe: 'Martinis and music.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 46, y: 56 },
        website: 'https://www.cheekymartinilounge.com/'
    },
    {
        id: 'oly-taproom',
        name: 'Oly Taproom',
        type: 'Taproom',
        vibe: 'Massive selection of taps by the water.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 30, y: 40 },
        website: 'https://www.olytaproom.com/'
    },
    {
        id: 'swing-wine-bar',
        name: 'Swing Wine Bar',
        type: 'Wine Bar',
        vibe: 'Elevated wine bar with a view.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 28, y: 38 },
        website: 'https://swingwinebar.com/'
    },
    {
        id: 'rumors-wine-bar',
        name: 'Rumors Wine Bar',
        type: 'Wine Bar',
        vibe: 'Cozy spot for wine lovers.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 50, y: 60 },
        website: 'https://www.rumorswinebar.com/'
    },
    {
        id: 'the-wine-loft',
        name: 'The Wine Loft',
        type: 'Wine Bar',
        vibe: 'Intimate loft setting for wine.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 52, y: 62 },
        website: 'https://the-wine-loft-1.wheree.com/'
    },
    {
        id: 'legends-arcade',
        name: 'Legends Arcade',
        type: 'Arcade Bar',
        vibe: 'Retro arcade games and beer.',
        status: 'lively',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 55, y: 55 },
        website: 'https://www.legends-arcade.com/'
    },
    {
        id: 'the-cove',
        name: 'The Cove',
        type: 'Bar',
        vibe: 'Local favorite.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 60, y: 50 },
        website: 'https://www.coveolympia.com/'
    },
    {
        id: 'mcmenamins-spar-cafe',
        name: 'McMenamins Spar Cafe',
        type: 'Pub',
        vibe: 'Historic McMenamins vibe.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 45, y: 45 },
        website: 'https://www.mcmenamins.com/spar-cafe',
        isHistoricalAnchor: true,
        historySnippet: "Sit in the original booths where the loggers drank."
    },
    {
        id: 'hannahs',
        name: 'Hannah’s Bar & Grille',
        type: 'Bar',
        vibe: 'Classic American bar and grill.',
        status: 'lively',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 50, y: 50 },
        website: 'https://hannahsoly.com/'
    },
    {
        id: 'charlies-bar-grill',
        name: 'Charlie’s Bar & Grill',
        type: 'Bar',
        vibe: 'Sports, food, and drinks.',
        status: 'lively',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 48, y: 48 },
        website: 'https://www.charlieson4th.com/'
    },
    {
        id: 'wild-child',
        name: 'Wild Child',
        type: 'Bar',
        vibe: 'Modern and energetic.',
        status: 'lively',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 49, y: 49 },
        website: 'https://wildchildolympia.com/'
    },
    {
        id: 'the-bus-stop',
        name: 'The Bus Stop',
        type: 'Bar',
        vibe: 'Wait for the bus, grab a drink.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 47, y: 47 },
        website: 'https://www.thebusstopolympia.com/'
    },
    {
        id: 'octapas-cafe',
        name: 'Octapas Cafe',
        type: 'Cafe/Bar',
        vibe: 'Great food and atmosphere.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 43, y: 43 },
        website: 'https://octapascafe.com/'
    },
    {
        id: 'chicory',
        name: 'Chicory',
        type: 'Restaurant/Bar',
        vibe: 'Upscale dining and drinks.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 41, y: 41 },
        website: 'https://www.chicoryrestaurant.com/'
    },
    {
        id: 'cynara',
        name: 'Cynara Restaurant & Lounge',
        type: 'Lounge',
        vibe: 'Elegant dining and lounge.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 39, y: 39 },
        website: 'https://cynaraolympia.com/'
    },
    {
        id: 'equal-latin',
        name: 'Equal Latin Restaurant & Bar',
        type: 'Bar',
        vibe: 'Latin flavors and drinks.',
        status: 'lively',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 37, y: 37 },
        website: 'https://www.experienceolympia.com/directory/equal-latin-restaurant-bar/'
    },
    {
        id: 'uptown-grill',
        name: 'Uptown Grill',
        type: 'Grill',
        vibe: 'Fine food in the uptown area.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 35, y: 35 },
        website: 'https://www.uptowngrill514.com/'
    },
    {
        id: 'le-voyeur',
        name: 'Le Voyeur',
        type: 'Bar',
        vibe: 'Punk rock vegetarian/vegan spot.',
        status: 'lively',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 33, y: 33 },
        website: 'http://www.levoyeurolympia.com/'
    },
    {
        id: 'altitude-15',
        name: 'Altitude 15 / ACME',
        type: 'Bar',
        vibe: 'Grand opening energy.',
        status: 'buzzing',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 31, y: 31 },
        website: 'https://www.acmebarandcompany.com/'
    },
    {
        id: '4th-ave-tavern',
        name: '4th Ave Tavern',
        type: 'Tavern',
        vibe: 'Olympia classic.',
        status: 'lively',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 29, y: 29 },
        website: 'https://www.experienceolympia.com/directory/4th-ave-tavern/'
    },

    // --- GHOST LIST (Inactive/Scrubbed per Audit) ---
    {
        id: 'heritage-distilling',
        name: 'Heritage Distilling (Tumwater)',
        type: 'Distillery',
        isActive: false,
        isVisible: false,
        originStory: "Closed effective Dec 31, 2025. Pivoted to wholesale/Tribal partnership model."
    },
    {
        id: 'locust-cider',
        name: 'Locust Cider (Olympia)',
        type: 'Cidery',
        isActive: false,
        isVisible: false,
        originStory: "Permanently closed."
    },
    {
        id: 'finnriver-tumwater',
        name: 'Finnriver (Tumwater)',
        type: 'Cidery',
        isActive: false,
        isVisible: false,
        originStory: "Permanently closed. Failed to gain traction in the Craft District."
    },
    {
        id: 'fish-tale-brewpub-legacy',
        name: 'Fish Tale Brewpub',
        type: 'Brewery',
        isActive: false,
        isVisible: false,
        originStory: "Entity is dead. Succeeded by Ilk Lodge."
    },
    {
        id: 'madsen-family-cellars',
        name: 'Madsen Family Cellars',
        type: 'Winery',
        isActive: false,
        isVisible: false
    },
    {
        id: 'scatter-creek-winery',
        name: 'Scatter Creek Winery',
        type: 'Winery',
        isActive: false,
        isVisible: false
    }
];

async function clearCollection(collectionName: string) {
    const snapshot = await db.collection(collectionName).get();
    const batch = db.batch();
    snapshot.docs.forEach((doc) => batch.delete(doc.ref));
    await batch.commit();
    console.log(`Cleared collection: ${collectionName}`);
}

async function seedVenues() {
    console.log('Starting venue seeding with clean slate...');
    try {
        await clearCollection('venues');
        await clearCollection('signals');

        const venuesRef = db.collection('venues');
        for (const venue of venues) {
            const { id, ...venueData } = venue;

            // Default to Paid League Member for all active venues (User Request Dec 24)
            const isPaid = venueData.isActive !== false && (venue as any).isPaidLeagueMember !== false;

            await venuesRef.doc(id).set({
                ...venueData,
                isPaidLeagueMember: isPaid
            });
            console.log(`Seeded venue: ${venue.name} (${id})`);
        }
        console.log('Seeding complete! 🍺');
        process.exit(0);
    } catch (error) {
        console.error('Error seeding venues:', error);
        process.exit(1);
    }
}

seedVenues();
