import { db } from './firebaseAdmin';

const venues = [
    // --- DOWNTOWN WALKABLE LOOP ---
    {
        id: 'well-80',
        name: 'Well 80 Artesian Brewing',
        venueType: 'brewery_taproom',
        vibeTags: [],
        foodService: 'full_kitchen',
        status: 'buzzing',
        checkIns: 0,
        isPaidLeagueMember: true,
        vibe: 'Home of Artie and built on the Artesian Well',
        insiderVibe: "It's slick. Maybe too slick? It feels like a brewpub, not a bar—lots of polished concrete and big screens. But you can't argue with the history. Tapping that well is a boss move, and the 'Leopold's #1 Lager' is legit respect to the old school. It's where you go to watch the game, not to hide from the world.",
        originStory: "They literally drilled a hole in the floor to tap into the same mythical aquifer that made Olympia Beer famous in 1896. It's a shiny, high-energy brewpub built directly on top of history, serving crisp lagers made from the 'Water' that put this town on the map.",
        geoLoop: 'Downtown_Walkable',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        coordinates: { x: 55, y: 85 },
        location: { lat: 47.045402, lng: -122.895869 },
        address: '514 4th Ave E, Olympia, WA 98501, USA',
        isActive: true,
        isVisible: true,
        isHistoricalAnchor: true,
        historySnippet: "Taste the water (literally) from the original Artesian Well.",
        flashDeals: [{
            id: 'fd-w80-01',
            venueId: 'well-80',
            title: '$2 Pretzels & Cheese',
            description: 'Flash Deal: $2 Pretzels valid for next 45 mins.',
            startTime: Date.now(),
            endTime: Date.now() + 45 * 60 * 1000,
            isApproved: true,
            termsAccepted: true,
            active: true
        }],
        activeFlashDealId: 'fd-w80-01',
        deal: "$2 Pretzels & Cheese",
        dealEndsIn: 45,
        vibeDefault: 'LIVELY',
        happyHourSpecials: "$1 OFF PINTS & LEOPOLD PRETZELS",
        happyHour: {
            startTime: '15:00',
            endTime: '18:00',
            description: '$1 Off Pints & Leopold Pretzels',
            days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
        },
        gameFeatures: [], // No specific games listed
        ownerId: "KU9KvRYzzrZfVU7BV4gaPYAFlKS2",
        managerIds: ["KU9KvRYzzrZfVU7BV4gaPYAFlKS2"],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Lively' },
        fullMenu: [
            {
                id: 'menu-1',
                name: 'Leopold\'s #1 Lager',
                type: 'Crisp',
                description: 'The original 1896 recipe. Crisp, clean, and historic.',
                stats: { abv: 4.8, ibu: 25, price: '$7' },
                margin_tier: 'High',
                source: 'Internal_Library',
                status: 'Live',
                last_toggled_at: Date.now()
            },
            {
                id: 'menu-2',
                name: 'Volcanic Ash IPA',
                type: 'Hoppy',
                description: 'Hazy, juicy, and explosive. Citra and Mosaic hops.',
                stats: { abv: 7.2, ibu: 65, price: '$8' },
                margin_tier: 'Medium',
                source: 'Untappd',
                status: 'Live',
                last_toggled_at: Date.now()
            },
            {
                id: 'menu-3',
                name: 'Darkness Imperial Stout',
                type: 'Dark',
                description: 'Aged in bourbon barrels. Thick, chocolatey, and dangerous.',
                stats: { abv: 11.5, ibu: 80, price: '$12' },
                margin_tier: 'High',
                source: 'Manual',
                status: 'Live',
                last_toggled_at: Date.now()
            },
            {
                id: 'menu-4',
                name: 'Truffle Fries',
                type: 'Food',
                description: 'Crispy fries, parmesan, truffle oil, garlic aioli.',
                stats: { price: '$9' },
                margin_tier: 'High',
                source: 'Manual',
                status: 'Live',
                last_toggled_at: Date.now()
            },
            {
                id: 'menu-5',
                name: 'Seasonal Sour',
                type: 'Sour',
                description: 'Rotating seasonal fruit sour. Ask server for details.',
                stats: { abv: 5.5, price: '$8' },
                margin_tier: 'High',
                source: 'Internal_Library',
                status: 'Library',
                last_toggled_at: Date.now()
            }
        ]
    },
    {
        id: 'ilk-lodge',
        name: 'Ilk Lodge',
        venueType: 'brewery_taproom',
        vibeTags: ['dive'],
        foodService: 'limited_kitchen', // Smash burgers
        status: 'chill',
        checkIns: 0,
        vibe: 'Twin Peaks meets Skate Rat',
        insiderVibe: "Pat Jansen is a legend. He ran the brewing at Three Mags, then Matchless, now this. The vibe is 'Twin Peaks meets Skate Rat.' It's cool without trying. And the burgers? Greasy, smashy perfection. This replaces Fish Tale as the soul of downtown brewing.",
        originStory: "When the legendary Fish Tale Brewpub died, the former brewers of Matchless and Three Magnets didn't just mourn—they took it over. Now it's a 'lodge' serving high-technique ales and arguably the best smash burgers in the county, resurrecting the most iconic corner in Olympia nightlife.",
        geoLoop: 'Downtown_Walkable',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        coordinates: { x: 48, y: 72 },
        location: { lat: 47.043854, lng: -122.896660 },
        address: '515 Jefferson St SE, Olympia, WA 98501, USA',
        isActive: true,
        isVisible: true,
        vibeDefault: 'CHILL',
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Lively' }
    },
    {
        id: 'headless-mumby',
        name: 'Headless Mumby Brewing Company',
        venueType: 'brewery_taproom',
        vibeTags: [],
        foodService: 'none_byof',
        status: 'chill',
        checkIns: 0,
        vibe: 'Union-made lagers; no IPAs here',
        insiderVibe: "Finally. A place that doesn't taste like a pine cone. Alex is a worker; he's union. This place has 'working class hero' vibes but in a cozy way. It feels like a living room. No kitchen, which is perfect—let people order pizza from Vic's across the street. The staff doesn't have to fuss with food, they just pour beer.",
        originStory: "Founded by Alex Maffeo, a union tradesman who decided the world had enough IPAs, this Westside gem brews only lagers—crisp, clean, and unpretentious. It's named after a Warren Zevon song about a headless gunner and an old local shingle mill, proving they care more about cool stories and cold beer than chasing trends.",
        geoLoop: 'Downtown_Walkable',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        coordinates: { x: 30, y: 70 },
        location: { lat: 47.046841, lng: -122.925583 },
        address: '232 Division St NW, Olympia, WA 98502, USA',
        isActive: true,
        isVisible: true,
        vibeDefault: 'CHILL',
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' }
    },
    {
        id: 'three-magnets',
        name: 'Three Magnets Brewing Co.',
        venueType: 'brewery_taproom',
        vibeTags: [],
        foodService: 'full_kitchen',
        status: 'buzzing',
        checkIns: 0,
        vibe: 'The Community Hub & NA Pioneers',
        insiderVibe: "The center of the 'Sober Squad' league track. Home of 'Self Care' non-alcoholic beer and Scherler Sundays.",
        originStory: "Sara and Nate Reilly built a 'Third Place' for Olympia. Their pivot to 'Self Care' (a non-alcoholic line) has made them a national player in the sober-curious movement.",
        geoLoop: 'Downtown_Walkable',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        isSoberFriendly: true,
        coordinates: { x: 52, y: 65 },
        location: { lat: 47.043153, lng: -122.898526 },
        address: '600 Franklin St SE STE 105, Olympia, WA 98501, USA',
        isActive: true,
        isVisible: true,
        vibeDefault: 'LIVELY',
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Lively' }
    },
    {
        id: 'whitewood-cider',
        name: 'Whitewood Cider Co.',
        venueType: 'brewery_taproom',
        vibeTags: [],
        foodService: 'none_byof',
        status: 'chill',
        checkIns: 0,
        vibe: 'The Teeny Tiny Taproom',
        insiderVibe: "The Teeny Tiny Taproom is the definition of cool. It's barely a room. You sit on the patio, you drink cider that tastes like actual apples, not candy. It's legit. No frills, just product.",
        originStory: "Dave White was writing about cider before anyone was drinking it. He founded the Northwest Cider Association and then put his money where his mouth was, creating a 'Teeny Tiny Taproom' in downtown Oly that is smaller than most walk-in closets but pours the most respected heirloom ciders in the state. They recently moved production to Tenino, but the heart remains in that tiny room on 4th Ave.",
        geoLoop: 'Downtown_Walkable',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        isBoutique: true,
        isLowCapacity: true,
        coordinates: { x: 60, y: 40 },
        location: { lat: 47.045669, lng: -122.893349 },
        address: '728 4th Ave E, Olympia, WA 98506, USA',
        isActive: true,
        isVisible: true,
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' }
    },
    {
        id: 'endless-sound-cellars',
        name: 'Endless Sound Cellars',
        venueType: 'bar_pub',
        vibeTags: ['wine_focus'],
        foodService: 'snacks',
        status: 'chill',
        checkIns: 0,
        vibe: 'The Urban Cellar',
        insiderVibe: "A sleek, industrial cellar feel inside the 222 Market. Perfect for a sophisticated evening flight.",
        originStory: "Mark Bosso brought his winemaking chops from Woodinville to the heart of downtown Olympia. It's the perfect 'urban winery' experience.",
        geoLoop: 'Downtown_Walkable',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        coordinates: { x: 65, y: 45 },
        location: { lat: 47.046434, lng: -122.901569 },
        address: '222 Capitol Way N, Olympia, WA 98501, USA',
        isActive: true,
        isVisible: true,
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' }
    },

    // --- WAREHOUSE TUMWATER LOOP ---
    {
        id: 'matchless-brewing',
        name: 'Matchless Brewing',
        venueType: 'brewery_taproom',
        vibeTags: [],
        foodService: 'snacks',
        status: 'buzzing',
        checkIns: 0,
        vibe: 'The Hype Beast; 80s Synth-Pop Vibes',
        insiderVibe: "The branding is incredible. Best cans in the county. The vibe in the taproom is industrial but energetic. It feels like a place where beer nerds congregate. It's legit.",
        originStory: "Born from the creative minds of Three Magnets alumni, Matchless exploded onto the scene with branding that looks like an 80s synth-pop album cover and beer that pushes every boundary. They don't just make IPAs; they make hazy, juicy, complex hop-bombs that win awards and wreck palates in the best way possible.",
        geoLoop: 'Warehouse_Tumwater',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        coordinates: { x: 50, y: 15 },
        location: { lat: 46.970873, lng: -122.884999 },
        address: '8036 River Dr SE #208, Tumwater, WA 98501, USA',
        isActive: true,
        isVisible: true,
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Lively' }
    },
    {
        id: 'triceratops-brewing',
        name: 'Triceratops Brewing Company',
        venueType: 'brewery_taproom',
        vibeTags: [],
        foodService: 'none_byof',
        status: 'chill',
        checkIns: 0,
        vibe: 'Approachably dangerous, family founded',
        insiderVibe: "The Strawberry Golden is a gateway drug for my wine drinkers. It's sophisticated enough, not cloyingly sweet. It allows a wine drinker to participate in a brewery crawl without grimacing.",
        originStory: "Rob and Kelly Horn moved here from New Jersey and started brewing in their garage before taking over a warehouse space near the airport. Named after their three kids (the 'three horns'), they brew approachable, dangerously drinkable beers like the 'Strawberry Golden Ale' that convert even non-beer drinkers.",
        geoLoop: 'Warehouse_Tumwater',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        coordinates: { x: 51, y: 16 },
        location: { lat: 46.970596, lng: -122.884697 },
        address: '8036 River Dr SE #203, Tumwater, WA 98501, USA',
        isActive: true,
        isVisible: true,
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' }
    },
    {
        id: 'rainwater-brewing',
        name: 'Rainwater Brewing',
        venueType: 'brewery_taproom',
        vibeTags: [],
        foodService: 'snacks',
        status: 'chill',
        checkIns: 0,
        vibe: 'The Merchant Mariner; Steady hand at the wheel',
        insiderVibe: "I liked Hoh River; it was weird. Rainwater feels like a steady hand took the wheel. The merchant mariner backstory is cool—authentic grit. It feels like a place where actual work gets done.",
        originStory: "Gavin Rainwater, a former merchant mariner who spent years at sea, dropped anchor in Tumwater to take over the old Hoh River Brewery. It's a true 'local's local' spot, serving unpretentious suds and honest food in a space that feels like a warm, dry cabin in the middle of a PNW storm.",
        geoLoop: 'Warehouse_Tumwater',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        coordinates: { x: 45, y: 20 },
        location: { lat: 47.025694, lng: -122.934032 },
        address: '2442 Mottman Rd SW, Tumwater, WA 98512, USA',
        isActive: true,
        isVisible: true,
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' }
    },
    {
        id: 'mount-olympus',
        name: 'Mount Olympus Brewing (Tumwater Taps)',
        venueType: 'brewery_taproom',
        vibeTags: [],
        foodService: 'full_kitchen',
        status: 'buzzing',
        checkIns: 0,
        vibe: 'The District Anchor; Aberdeen Grit',
        insiderVibe: "Aberdeen grit in a polished Tumwater building. Rowdy in a good way, designed for loud laughs and big groups.",
        originStory: "A martial arts-loving brewery from Aberdeen that decided to conquer the valley. They are the new anchor of the Tumwater Craft District.",
        geoLoop: 'Warehouse_Tumwater',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        coordinates: { x: 48, y: 12 },
        location: { lat: 47.009579, lng: -122.905463 },
        address: '4242 Capitol Blvd SE Suite 100, Olympia, WA 98502, USA',
        isActive: true,
        isVisible: true,
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Loud/Music' }
    },

    // --- DESTINATION QUESTS ---
    {
        id: 'top-rung',
        name: 'Top Rung Brewing Company',
        venueType: 'brewery_taproom',
        vibeTags: [],
        foodService: 'snacks',
        status: 'chill',
        checkIns: 0,
        vibe: 'The Outpost; precision and brotherhood',
        insiderVibe: "It's in a warehouse district in Lacey. It's not 'cool' in the hipster sense, but it's honest. It's where you go after a shift. I respect it. No pretense.",
        originStory: "Founded by Casey Sobol and Jason Stoltz, two career firefighters who spent their downtime perfecting recipes, this Lacey brewery is built on service, precision, and the brotherhood of the firehouse. It's an unpretentious warehouse taproom where the 'My Dog Scout Stout' has won more medals than most generals.",
        geoLoop: 'Destination_Quest',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        coordinates: { x: 85, y: 15 },
        location: { lat: 47.075868, lng: -122.763229 },
        address: '8343 Hogum Bay Ln NE, Lacey, WA 98516, USA',
        isActive: true,
        isVisible: true,
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' }
    },
    {
        id: 'sandstone-distillery',
        name: 'Sandstone Distillery',
        venueType: 'bar_pub',
        vibeTags: ['cocktail_focus'],
        foodService: 'snacks',
        status: 'chill',
        checkIns: 0,
        vibe: 'The Pilgrimage; Rugged and Authentic',
        insiderVibe: "A world-class educational stop. The bacon whiskey is a conversation starter, but the gin is the real deal.",
        originStory: "John Bourdon built a shrine to Tenino's stone-carving history. Grain-to-glass ruggedness fueled by locally grown grain and cooled by rainwater.",
        geoLoop: 'Destination_Quest',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        coordinates: { x: 70, y: 10 },
        location: { lat: 46.869615, lng: -122.903386 },
        address: '842 Wright Rd SE, Tenino, WA 98589, USA',
        isActive: true,
        isVisible: true,
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' }
    },
    {
        id: 'talking-cedar',
        name: 'Talking Cedar',
        venueType: 'brewery_taproom',
        vibeTags: [],
        foodService: 'full_kitchen',
        status: 'buzzing',
        checkIns: 0,
        vibe: 'The Monument; Sovereign Spirits',
        insiderVibe: "It took an act of Congress to build this. A monument to sovereignty and spirits, partnering with Heritage to build a state-of-the-art facility.",
        originStory: "The Chehalis Tribe fought to repeal an 1834 law banning distilleries on tribal land. It is a massive facility dedicated to craft and heritage.",
        geoLoop: 'Destination_Quest',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        coordinates: { x: 10, y: 10 },
        location: { lat: 46.801865, lng: -123.015511 },
        address: '19770 Sargent Rd SW, Rochester, WA 98579, USA',
        isActive: true,
        isVisible: true,
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Lively' }
    },
    {
        id: 'axis-meads',
        name: 'Axis Meads',
        venueType: 'bar_pub',
        vibeTags: ['wine_focus'], // Meads logic
        foodService: 'none_byof',
        status: 'chill',
        checkIns: 0,
        vibe: 'The Rare Drop; Spiced Honey Adventures',
        insiderVibe: " Spicy habanero and ginger meads that drink like cocktails. Located in the heart of Lacey's industrial zone.",
        originStory: "Born from the back room of the legendary Skep & Skein. Dave Ross crafts meads that destroy the cloyingly sweet stereotype.",
        geoLoop: 'Destination_Quest',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        coordinates: { x: 82, y: 22 },
        location: { lat: 47.070649, lng: -122.780222 },
        address: '2633 Willamette Dr NE suite b, Lacey, WA 98516, USA',
        isActive: true,
        isVisible: true,
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' }
    },
    {
        id: 'stottle-winery',
        name: 'Stottle Winery',
        venueType: 'bar_pub',
        vibeTags: ['wine_focus'],
        foodService: 'snacks',
        status: 'chill',
        checkIns: 0,
        vibe: 'The Industrial Anchor; Serious chemistry',
        insiderVibe: "High quality product. Josh knows his chemistry. It appeals to the 'Wine Snob' demographic.",
        originStory: "Josh Stottlemyer traded web development for winemaking, setting up shop in a Lacey industrial park to prove you don't need a chateau to make world-class Syrah. It's a serious winery for serious wine drinkers, stripping away the pretension to focus entirely on what's in the glass.",
        geoLoop: 'Destination_Quest',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        coordinates: { x: 83, y: 25 },
        location: { lat: 47.072335, lng: -122.756721 },
        address: '2641 Willamette Dr NE ste e, Lacey, WA 98516, USA',
        isActive: true,
        isVisible: true,
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' }
    },
    {
        id: 'medicine-creek',
        name: 'Medicine Creek Winery',
        venueType: 'bar_pub',
        vibeTags: ['wine_focus'],
        foodService: 'snacks',
        status: 'chill',
        checkIns: 0,
        vibe: 'The Hideaway; Stagecoach-stop fantasy',
        insiderVibe: "Jim Myers (a dentist with a cowboy soul) transformed a potato barn into an 1800s New Orleans brothel-themed tasting room.",
        originStory: "Operating in the Nisqually Valley, this is a stagecoach-stop fantasy come to life, pouring big, bold Washington reds.",
        geoLoop: 'Destination_Quest',
        isVerifiedMaker: true,
        isLocalMaker: true,
        physicalRoom: true,
        coordinates: { x: 90, y: 30 },
        location: { lat: 47.048480, lng: -122.712242 },
        address: '947 Old Pacific Hwy SE, Olympia, WA 98513, USA',
        isActive: true,
        isVisible: true,
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' }
    },
    {
        id: 'elk-pond-ales',
        name: 'Elk Pond Craft Ales',
        venueType: 'brewery_taproom',
        vibeTags: [],
        foodService: 'none_byof',
        status: 'chill',
        checkIns: 0,
        vibe: 'The Easter Egg; Scavenger Hunt Target',
        insiderVibe: "We can't send people to them. They don't exist as a venue. But we can gamify the hunt. 'Find the Elk'—extra points for checking in a pint of Elk Pond at a partner bar. It encourages exploration of other venues.",
        originStory: "The 'Ghost Brewery' of Olympia. The Wilkinson family built a dedicated micro-brewery on their property in 2023, but they don't open their doors to the public. You have to hunt for their kegs at local taverns like Pints Barn or Character's Corner to taste their 'Gold Craft' creations.",
        physicalRoom: false,
        geoLoop: 'Destination_Quest',
        isVerifiedMaker: true,
        isLocalMaker: true,
        coordinates: { x: 80, y: 20 },
        isActive: true,
        isVisible: true,
        scavengerHunts: [
            {
                title: 'Find the Elk!',
                partnerVenues: ['brotherhood-lounge'],
                badgeId: 'elk-pond-finder'
            }
        ],
        gameFeatures: [],
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' }
    },

    // --- RECONCILED VENUES (Added Dec 2025) ---
    {
        id: 'brotherhood-lounge',
        name: 'The Brotherhood Lounge',
        venueType: 'bar_pub',
        vibeTags: ['dive'],
        amenities: ['Pool', 'Shuffleboard'],
        foodService: 'none_byof',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: false, noise_level: 'Loud/Music' },
        vibe: 'Industrial grit, stiff drinks, and shuffleboard.',
        status: 'buzzing',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 45, y: 55 },
        location: { lat: 47.048380, lng: -122.902270 },
        address: '119 Capitol Way N, Olympia, WA 98501, USA',
        website: 'https://thebrotherhoodlounge.com/',
        physicalRoom: true,
        // Happy Hour (Scheduled)
        happyHour: {
            startTime: '16:00',
            endTime: '19:00',
            description: '$4 Wells & $1 Off Drafts',
            days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
        },
        isHistoricalAnchor: true,
        historySnippet: "Rumored entrance to the tunnels and Oly's oldest bar.",
        cheatCodeUrl: '/history/tunnels-of-olympia',
        isPaidLeagueMember: true,
        hasGameVibeCheckEnabled: true,
        gameFeatures: [
            { id: 'pool_1', type: 'pool_table', name: 'Pool Table', count: 1, status: 'active' },
            { id: 'shuffleboard_1', type: 'shuffleboard', name: 'Shuffleboard Table', count: 1, status: 'active' },
            { id: 'arcade_1', type: 'arcade_game', name: 'Retro Arcade Game', count: 1, status: 'active' }
        ],
        liveGameStatus: {}
    },
    {
        id: 'mccoys-tavern',
        name: 'McCoy’s Tavern',
        venueType: 'bar_pub',
        vibeTags: ['dive'],
        foodService: 'none_byof',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: false, noise_level: 'Loud/Music' },
        vibe: 'The legendary downtown dive. No frills.',
        status: 'buzzing',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 40, y: 50 },
        location: { lat: 47.045408, lng: -122.897171 },
        address: '418 4th Ave E, Olympia, WA 98501, USA',
        gameFeatures: [
            { id: 'pool_1', type: 'pool_table', name: 'Pool Table', count: 2, status: 'active' },
            { id: 'darts_1', type: 'darts', name: 'Darts', count: 2, status: 'active' }
        ],
        special_events: [
            {
                id: 'evt-mccoys-1',
                title: 'The Olson Bros Band',
                date: new Date().toISOString().split('T')[0], // Today
                startTime: '20:00',
                type: 'music',
                is_featured: true,
                description: 'Live Country Rock from the PNW.'
            },
            {
                id: 'evt-mccoys-2',
                title: 'Halloween Bash',
                date: '2025-10-31',
                startTime: '21:00',
                type: 'special',
                description: 'Costume contest and spooky vibes.'
            }
        ]
    },
    {
        id: 'eastside-club-tavern',
        name: 'The Eastside Club Tavern',
        venueType: 'bar_pub',
        vibeTags: ['dive'],
        foodService: 'snacks', // Popcorn
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: false, noise_level: 'Lively' },
        vibe: 'Old school olympia. Great beer selection.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 60, y: 60 },
        address: '410 4th Ave E, Olympia, WA 98501, USA',
        website: 'http://www.theeastsideclub.com/',
        location: { lat: 47.0461, lng: -122.8933 },
        gameFeatures: [
            { id: 'pool_1', type: 'pool_table', name: 'Pool Table', count: 2, status: 'active' },
            { id: 'shuffleboard_1', type: 'shuffleboard', name: 'Shuffleboard', count: 1, status: 'active' }
        ]
    },
    {
        id: 'shiny-prize',
        name: 'Shiny Prize',
        venueType: 'bar_pub',
        vibeTags: ['cocktail_focus', 'dive'],
        foodService: 'snacks',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: false, noise_level: 'Conversational' },
        vibe: 'Mid-century modern aesthetic with top-tier cocktails.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 35, y: 45 },
        location: { lat: 47.045053, lng: -122.900817 },
        address: '118 4th Ave E, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.shinyprize.com/',
        gameFeatures: []
    },
    {
        id: 'nicoles-bar',
        name: 'Nicole’s Bar',
        venueType: 'bar_pub',
        vibeTags: ['dive', 'sports'],
        foodService: 'full_kitchen',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Lively' },
        vibe: 'Downtown staple for good food and drinks.',
        status: 'buzzing',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 42, y: 52 },
        location: { lat: 47.043006, lng: -122.901831 },
        address: '109 Legion Way SW, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://nicolesbar.com/',
        // Happy Hour (Scheduled)
        happyHour: {
            startTime: '15:30',
            endTime: '18:30',
            description: '$2 Domestic Cans & Basket Specials',
            days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
        },
        happyHourSpecials: "$2 DOMESTIC CANS & BASKET SPECIALS",
        gameFeatures: []
    },
    {
        id: 'cryptatropa-bar',
        name: 'Cryptatropa Bar',
        venueType: 'lounge_club',
        vibeTags: ['cocktail_focus'], // speakeasy vibe
        foodService: 'none_byof',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: false, noise_level: 'Loud/Music' },
        vibe: 'Goth-industrial haven. Dark and moody.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 38, y: 48 },
        location: { lat: 47.045430, lng: -122.897140 },
        address: '421 4th Ave E, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.thecryptbar.com/',
        gameFeatures: []
    },
    {
        id: 'jakes-on-4th',
        name: 'Jake’s on 4th',
        venueType: 'bar_pub',
        vibeTags: ['dive', 'sports'],
        foodService: 'full_kitchen',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Lively' },
        vibe: 'Classic bar returned to its roots.',
        status: 'buzzing',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 41, y: 51 },
        location: { lat: 47.044870, lng: -122.898593 },
        address: '311 4th Ave E, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.southsoundreport.com/p/jake-s-on-4th-returns-to-downtown-olympia',
        gameFeatures: []
    },
    {
        id: 'filibuster',
        name: 'Filibuster',
        venueType: 'bar_pub',
        vibeTags: ['cocktail_focus'],
        foodService: 'none_byof',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: false, noise_level: 'Conversational' },
        vibe: 'Upscale cocktails and lounge atmosphere.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 44, y: 54 },
        location: { lat: 47.044722, lng: -122.900194 },
        address: '404 Washington St SE, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://filibusterlounge.com/',
        gameFeatures: []
    },
    {
        id: 'cheeky-martini-lounge',
        name: 'Cheeky Martini Lounge',
        venueType: 'lounge_club',
        vibeTags: ['cocktail_focus'],
        foodService: 'snacks',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: false, noise_level: 'Lively' },
        vibe: 'Martinis and music.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 46, y: 56 },
        location: { lat: 47.044722, lng: -122.900194 },
        address: '404 Washington St SE, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.cheekymartinilounge.com/',
        gameFeatures: []
    },
    {
        id: 'oly-taproom',
        name: 'Oly Taproom',
        venueType: 'brewery_taproom',
        vibeTags: [],
        foodService: 'snacks',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Lively' },
        vibe: 'Massive selection of taps by the water.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 30, y: 40 },
        location: { lat: 47.046883, lng: -122.902828 },
        address: '312 Columbia St NW, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.olytaproom.com/',
        gameFeatures: []
    },
    {
        id: 'swing-wine-bar',
        name: 'Swing Wine Bar',
        venueType: 'bar_pub',
        vibeTags: ['wine_focus', 'cocktail_focus'],
        foodService: 'full_kitchen',
        tier_config: { is_directory_listed: true, is_league_eligible: false },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' },
        vibe: 'Elevated wine bar with a view.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 28, y: 38 },
        location: { lat: 47.040638, lng: -122.902593 },
        address: '825 Columbia St SW, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://swingwinebar.com/',
        gameFeatures: []
    },
    {
        id: 'rumors-wine-bar',
        name: 'Rumors Wine Bar',
        venueType: 'bar_pub',
        vibeTags: ['wine_focus'],
        foodService: 'snacks',
        tier_config: { is_directory_listed: true, is_league_eligible: true }, // Assumed eligible since it's a bar
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' }, // Assumed
        vibe: 'Cozy spot for wine lovers.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 50, y: 60 },
        location: { lat: 47.044240, lng: -122.900204 },
        address: '430 Washington St SE, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.rumorswinebar.com/',
        gameFeatures: []
    },
    {
        id: 'the-wine-loft',
        name: 'The Wine Loft',
        venueType: 'bar_pub',
        vibeTags: ['wine_focus'],
        foodService: 'snacks',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' },
        vibe: 'Intimate loft setting for wine.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 52, y: 62 },
        location: { lat: 47.047461, lng: -122.903524 },
        address: '401 Columbia St NW, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://the-wine-loft-1.wheree.com/',
        gameFeatures: []
    },
    {
        id: 'legends-arcade',
        name: 'Legends Arcade',
        venueType: 'arcade_bar',
        vibeTags: [],
        foodService: 'snacks',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Loud/Music' },
        vibe: 'Retro arcade games and beer.',
        status: 'buzzing',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 55, y: 55 },
        location: { lat: 47.045686, lng: -122.901435 },
        address: '109 State Ave NE, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.legends-arcade.com/',
        gameFeatures: [
            { id: 'arcade_1', type: 'arcade_game', name: 'Retro Arcade Cabinet', count: 10, status: 'active' },
            { id: 'pinball_1', type: 'pinball_machine', name: 'Pinball', count: 5, status: 'active' },
            { id: 'skeeball_1', type: 'skeeball', name: 'Skee-ball', count: 2, status: 'active' }
        ]
    },
    {
        id: 'the-cove',
        name: 'The Cove',
        venueType: 'bar_pub',
        vibeTags: ['dive'],
        foodService: 'full_kitchen',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Lively' },
        vibe: 'Local favorite.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 60, y: 50 },
        location: { lat: 47.046914, lng: -122.902151 },
        address: '311 Capitol Way N, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.coveolympia.com/',
        gameFeatures: []
    },
    {
        id: 'mcmenamins-spar-cafe',
        name: 'McMenamins Spar Cafe',
        venueType: 'restaurant_bar',
        vibeTags: ['dive'],
        foodService: 'full_kitchen',
        tier_config: { is_directory_listed: true, is_league_eligible: false },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' },
        vibe: 'Historic McMenamins vibe.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 45, y: 45 },
        location: { lat: 47.045039, lng: -122.900960 },
        address: '114 4th Ave E, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.mcmenamins.com/spar-cafe',
        isHistoricalAnchor: true,
        historySnippet: "Sit in the original booths where the loggers drank.",
        gameFeatures: []
    },
    {
        id: 'hannahs',
        name: "Hannah's Bar & Grill",
        nicknames: ["Hannah's", "Hannahs", "The Grill", "Hannah's Bar"],
        weekly_schedule: { 'friday': ['Karaoke'] },
        venueType: 'bar_pub',
        vibeTags: ['dive', 'sports'],
        foodService: 'full_kitchen',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Loud/Music' },
        vibe: 'Classic bar and grill.',
        status: 'buzzing',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 50, y: 50 },
        location: { lat: 47.043830, lng: -122.902591 },
        address: '123 5th Ave SW, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://hannahsoly.com/',
        happyHour: {
            startTime: '15:00',
            endTime: '18:00',
            description: 'Classic Happy Hour',
            days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
        },
        leagueEvent: 'trivia',
        triviaTime: '19:00',
        isPaidLeagueMember: true,
        ownerId: "KU9KvRYzzrZfVU7BV4gaPYAFlKS2",
        managerIds: ["KU9KvRYzzrZfVU7BV4gaPYAFlKS2"],
        hasGameVibeCheckEnabled: true,
        gameFeatures: [
            { id: 'pool_1', type: 'pool_table', name: 'Front Pool Table', count: 1, status: 'active' },
            { id: 'pool_2', type: 'pool_table', name: 'Back Pool Table', count: 1, status: 'active' },
            { id: 'pacman', type: 'arcade_game', name: 'Pacman', count: 1, status: 'active' },
            { id: 'mspacman', type: 'arcade_game', name: 'Ms. Pacman', count: 1, status: 'active' },
            { id: 'pinball', type: 'pinball_machine', name: 'Pinball', count: 1, status: 'active' } // Assuming singular pinball
        ],
        liveGameStatus: {}
    },
    {
        id: 'charlies-bar-grill',
        name: 'Charlie’s Bar & Grill',
        venueType: 'bar_pub',
        vibeTags: ['sports', 'dive'],
        foodService: 'full_kitchen',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Loud/Music' },
        vibe: 'Sports, food, and drinks.',
        status: 'buzzing',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 48, y: 48 },
        location: { lat: 47.045479, lng: -122.893117 },
        address: '620 4th Ave E, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.charlieson4th.com/',
        gameFeatures: []
    },
    {
        id: 'wild-child',
        name: 'Wild Child',
        venueType: 'bar_pub',
        vibeTags: ['dive'],
        foodService: 'none_byof',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: false, noise_level: 'Loud/Music' },
        vibe: 'Modern and energetic.',
        status: 'buzzing',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 49, y: 49 },
        location: { lat: 47.045300, lng: -122.897272 },
        address: '414 4th Ave E, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://wildchildolympia.com/',
        gameFeatures: []
    },
    {
        id: 'the-bus-stop',
        name: 'The Bus Stop',
        venueType: 'bar_pub',
        vibeTags: ['dive'],
        foodService: 'none_byof',
        vibe: 'Wait for the bus, grab a drink.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 47, y: 47 },
        location: { lat: 47.042228, lng: -122.900771 },
        address: '107 7th Ave SE suite 101, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.thebusstopolympia.com/',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: false, noise_level: 'Loud/Music' },
        gameFeatures: []
    },
    {
        id: 'octapas-cafe',
        name: 'Octapas Cafe',
        venueType: 'restaurant_bar',
        vibeTags: [],
        foodService: 'full_kitchen',
        tier_config: { is_directory_listed: true, is_league_eligible: false },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' },
        vibe: 'Great food and atmosphere.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 43, y: 43 },
        location: { lat: 47.042798, lng: -122.903609 },
        address: '610 Water St SW, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://octapascafe.com/',
        gameFeatures: []
    },
    {
        id: 'chicory',
        name: 'Chicory',
        venueType: 'restaurant_bar',
        vibeTags: [],
        foodService: 'full_kitchen',
        tier_config: { is_directory_listed: true, is_league_eligible: false },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' },
        vibe: 'Upscale dining and drinks.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 41, y: 41 },
        location: { lat: 47.046399, lng: -122.901498 },
        address: '222 Capitol Way N, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.chicoryrestaurant.com/',
        gameFeatures: []
    },
    {
        id: 'cynara',
        name: 'Cynara Restaurant & Lounge',
        venueType: 'restaurant_bar',
        vibeTags: ['dive'],
        foodService: 'full_kitchen',
        tier_config: { is_directory_listed: true, is_league_eligible: false },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' },
        vibe: 'Elegant dining and lounge.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 39, y: 39 },
        location: { lat: 47.046809, lng: -122.902642 },
        address: '202 Columbia St NW, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://cynaraolympia.com/',
        gameFeatures: []
    },
    {
        id: 'equal-latin',
        name: 'Equal Latin Restaurant & Bar',
        venueType: 'restaurant_bar',
        vibeTags: [],
        foodService: 'full_kitchen',
        vibe: 'Latin flavors and drinks.',
        status: 'buzzing',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 37, y: 37 },
        location: { lat: 47.043662, lng: -122.861062 },
        address: '2752 Pacific Ave SE, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.experienceolympia.com/directory/equal-latin-restaurant-bar/',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Lively' },
        gameFeatures: []
    },
    {
        id: 'uptown-grill',
        name: 'Uptown Grill',
        venueType: 'restaurant_bar',
        vibeTags: [],
        foodService: 'full_kitchen',
        tier_config: { is_directory_listed: true, is_league_eligible: false },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Conversational' },
        vibe: 'Fine food in the uptown area.',
        status: 'chill',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 35, y: 35 },
        location: { lat: 47.043863, lng: -122.901298 },
        address: '514 Capitol Way S, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.uptowngrill514.com/',
        gameFeatures: []
    },
    {
        id: 'le-voyeur',
        name: 'Le Voyeur',
        venueType: 'bar_pub',
        vibeTags: ['dive'],
        foodService: 'full_kitchen',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: true, noise_level: 'Loud/Music' },
        vibe: 'Punk rock vegetarian/vegan spot.',
        status: 'buzzing',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 33, y: 33 },
        location: { lat: 47.045307, lng: -122.897736 },
        address: '404 4th Ave E, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'http://www.levoyeurolympia.com/',
        gameFeatures: []
    },
    {
        id: 'altitude-15',
        name: 'Altitude 15 / ACME',
        venueType: 'bar_pub',
        vibeTags: ['dive'],
        foodService: 'none_byof',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: false, noise_level: 'Loud/Music' },
        vibe: 'Grand opening energy.',
        status: 'buzzing',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 31, y: 31 },
        location: { lat: 47.045860, lng: -122.896670 },
        address: '416 State Ave NE, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.acmebarandcompany.com/',
        gameFeatures: [
            { id: 'pool_1', type: 'pool_table', name: 'Pool Table', count: 1, status: 'active' },
            { id: 'pinball_1', type: 'pinball_machine', name: 'Pinball', count: 1, status: 'active' }
        ]
    },
    {
        id: '4th-ave-tavern',
        name: '4th Ave Tavern',
        venueType: 'bar_pub',
        vibeTags: ['dive'],
        foodService: 'none_byof',
        tier_config: { is_directory_listed: true, is_league_eligible: true },
        attributes: { has_manned_bar: true, minors_allowed: false, noise_level: 'Loud/Music' },
        vibe: 'Olympia classic.',
        status: 'buzzing',
        geoLoop: 'Downtown_Walkable',
        isActive: true,
        isVisible: true,
        checkIns: 0,
        coordinates: { x: 29, y: 29 },
        location: { lat: 47.045112, lng: -122.899922 },
        address: '210 4th Ave E, Olympia, WA 98501, USA',
        physicalRoom: true,
        website: 'https://www.experienceolympia.com/directory/4th-ave-tavern/',
        gameFeatures: []
    },

    // --- GHOST LIST (Inactive/Scrubbed per Audit) ---
    {
        id: 'heritage-distilling',
        name: 'Heritage Distilling (Tumwater)',
        venueType: 'brewery_taproom', // Placeholders
        vibeTags: ['cocktail_focus'],
        foodService: 'none_byof',
        status: 'dead',
        checkIns: 0,
        vibe: 'Ghost',
        location: { lat: 47.010330, lng: -122.904396 },
        address: '4200 Capitol Blvd SE Suite 104, Tumwater, WA 98501, USA',
        isActive: false,
        isVisible: false,
        originStory: "Closed effective Dec 31, 2025. Pivoted to wholesale/Tribal partnership model.",
        tier_config: { is_directory_listed: false, is_league_eligible: false },
        attributes: { has_manned_bar: false, minors_allowed: false, noise_level: 'Conversational' },
        gameFeatures: []
    },
    {
        id: 'locust-cider',
        name: 'Locust Cider (Olympia)',
        venueType: 'brewery_taproom',
        vibeTags: [],
        foodService: 'none_byof',
        status: 'dead',
        checkIns: 0,
        vibe: 'Ghost',
        location: { lat: 47.046434, lng: -122.901569 },
        address: '222 Capitol Way N, Olympia, WA 98501, USA',
        isActive: false,
        isVisible: false,
        originStory: "Permanently closed.",
        tier_config: { is_directory_listed: false, is_league_eligible: false },
        attributes: { has_manned_bar: false, minors_allowed: false, noise_level: 'Conversational' },
        gameFeatures: []
    },
    {
        id: 'finnriver-tumwater',
        name: 'Finnriver (Tumwater)',
        venueType: 'brewery_taproom',
        vibeTags: [],
        foodService: 'none_byof',
        status: 'dead',
        checkIns: 0,
        vibe: 'Ghost',
        location: { lat: 47.009579, lng: -122.905463 },
        address: '4242 Capitol Blvd SE suite 111, Tumwater, WA 98501, USA',
        isActive: false,
        isVisible: false,
        originStory: "Permanently closed. Failed to gain traction in the Craft District.",
        tier_config: { is_directory_listed: false, is_league_eligible: false },
        attributes: { has_manned_bar: false, minors_allowed: false, noise_level: 'Conversational' },
        gameFeatures: []
    },
    {
        id: 'fish-tale-brewpub-legacy',
        name: 'Fish Tale Brewpub',
        venueType: 'brewery_taproom',
        vibeTags: [],
        foodService: 'full_kitchen',
        status: 'dead',
        checkIns: 0,
        vibe: 'Ghost',
        location: { lat: 47.043153, lng: -122.898526 },
        address: '600 Franklin St SE STE 105, Olympia, WA 98501, USA',
        isActive: false,
        isVisible: false,
        originStory: "Entity is dead. Succeeded by Ilk Lodge.",
        tier_config: { is_directory_listed: false, is_league_eligible: false },
        attributes: { has_manned_bar: false, minors_allowed: false, noise_level: 'Conversational' },
        gameFeatures: []
    },
    {
        id: 'madsen-family-cellars',
        name: 'Madsen Family Cellars',
        venueType: 'bar_pub',
        vibeTags: ['wine_focus'],
        foodService: 'none_byof',
        status: 'dead',
        checkIns: 0,
        vibe: 'Ghost',
        location: { lat: 47.070649, lng: -122.780222 },
        address: '2625 Reinhardt Ln NE Suite D, Lacey, WA 98516, USA',
        isActive: false,
        isVisible: false,
        tier_config: { is_directory_listed: false, is_league_eligible: false },
        attributes: { has_manned_bar: false, minors_allowed: false, noise_level: 'Conversational' },
        gameFeatures: []
    },
    {
        id: 'scatter-creek-winery',
        name: 'Scatter Creek Winery',
        venueType: 'bar_pub',
        vibeTags: ['wine_focus'],
        foodService: 'none_byof',
        status: 'dead',
        checkIns: 0,
        vibe: 'Ghost',
        location: { lat: 46.826059, lng: -122.955023 },
        address: '3442 180th Ave SW, Tenino, WA 98589, USA',
        isActive: false,
        isVisible: false,
        tier_config: { is_directory_listed: false, is_league_eligible: false },
        attributes: { has_manned_bar: false, minors_allowed: false, noise_level: 'Conversational' },
        gameFeatures: []
    }
];

async function clearCollection(collectionName: string) {
    const snapshot = await db.collection(collectionName).get();
    const batch = db.batch();
    snapshot.docs.forEach((doc) => batch.delete(doc.ref));
    await batch.commit();
    console.log(`Cleared collection: ${collectionName}`);
}

async function seedVenues() {
    console.log('Starting venue seeding with clean slate...');
    try {
        await clearCollection('venues');
        await clearCollection('signals');

        const venuesRef = db.collection('venues');
        for (const venue of venues) {
            const { id, ...venueData } = venue;

            // Default to Paid League Member for all active venues (User Request Dec 24)
            const isPaid = venueData.isActive !== false && (venue as any).isPaidLeagueMember !== false;

            await venuesRef.doc(id).set({
                ...venueData,
                isPaidLeagueMember: isPaid
            });
            console.log(`Seeded venue: ${venue.name} (${id})`);
        }
        console.log('Seeding complete! 🍺');
        process.exit(0);
    } catch (error) {
        console.error('Error seeding venues:', error);
        process.exit(1);
    }
}

seedVenues();
